name: Periodic Test

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '*/30 * * * *'

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v1
    - name: Compile test code
      run: lein cljsbuild once test
    - name: Serve the content
      working-directory: ./resources/public
      run: python3 -m http.server 3449 &
    - name: Install Puppeteer
      run: npm i puppeteer
    - name: Wait for server
      run: sleep 10s
    - name: Run tests
      run: node puppeteer-runner.js || node puppeteer-runner.js || node puppeteer-runner.js
